---

- src: ANXS.generic-users
  version: v1.1.0

- src: ANXS.monit
  version: v1.1.0

- src: ANXS.hostname

- name: ANXS.nginx
  src: https://github.com/ANXS/nginx
  version: b469b10482ef76385e6a1f3bcb7c7d713d927972

- name: ANXS.postgresql
  src: https://github.com/ANXS/postgresql
  version: b6b105cd3863ecfc0c3ba79c26ab6e73681934c8

- src: rvm.ruby

- name: Stouts.wale
  src: https://github.com/carlosfunk/Stouts.wale
  version: d3c1d1b24fb5636f072920077df5b18e2cffbb17

- src: thefinn93.letsencrypt

- src: geerlingguy.postfix

- src: nodesource.node

